import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'

const styles = {
  container: ``,
  main: `justify-center items-center gap-3`,
  footer: ``,
  timerWrapper: `z-2 p-[2rem] bg-black text-white`,
  timerInner: ``,
  timerSegment: ``,
  time: ``,
  label: ``,
}


const Home: NextPage = () => {
  const [days, setDays]= useState(0)
  const [hours, setHours]= useState(0)
  const [minutes, setMinutes]= useState(0)
  const [seconds, setSeconds]= useState(0)
  const [message, setMessage] = useState(false)

  useEffect(()=>{
    const target = new Date("12/31/2022 23:59:59");

    const interval = setInterval(()=>{
      const now = new Date();
      const difference = target.getTime() - now.getTime();

      const d = Math.floor(difference / (1000 * 60 * 60 * 24));
      setDays(d);

      const h = Math.floor(difference % (1000 * 60 * 60 * 24) / (1000 * 60 * 60 ));
      setHours(h);

      const m = Math.floor(difference % (1000 * 60 * 60) / (1000 * 60 ));
      setMinutes(m);

      const s = Math.floor(difference % (1000 * 60) / (1000));
      setSeconds(s);

      if (d <= 0 && h <= 0 && m <= 0 && s <= m) {setMessage(true)}
    },1000);

    return ()=> clearInterval(interval);
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Countdown Timer || Made with Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {message ? <h1>Happy New Year</h1> : (

      <main className={styles.main}>
        <div className={styles.timerWrapper}>
          <div className={styles.timerInner}>
            <div className={styles.timerSegment}>
              <span className={styles.time}>{days}</span>
              <span className={styles.label}>Days</span>
            </div>

            <div className={styles.timerSegment}>
              <span className={styles.time}>{hours}</span>
              <span className={styles.label}>Hours</span>
            </div>

            <div className={styles.timerSegment}>
              <span className={styles.time}>{minutes}</span>
              <span className={styles.label}>minutes</span>
            </div>

            <div className={styles.timerSegment}>
              <span className={styles.time}>{seconds}</span>
              <span className={styles.label}>seconds</span>
            </div>
          </div>
        </div>
      </main>
      )}
    </div>
  )
}

export default Home
